/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.inc;

import bean.Account;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import view1.PnTSBan;
import view1.PnNVChucVu;
import view1.PnNVLuongCoBan;
import view1.PnNVNhanVien;
import view1.PnNVThongKe;
import view1.PnNVThuNhap;
import view1.PnTSKhuVuc;
import view1.PnTSLoaiThucUong;
import view1.PnTSThongTinQuan;

/**
 *
 * @author homin
 */
public class PnTop extends javax.swing.JPanel {
    /**
     * Creates new form PnTop
     */
    private JButton btRecently=null;
    private JPanel pnCenter;
    private Account ac;
    public PnTop(PnCenter pn,Account a) {
        initComponents();
       pnCenter=pn ;
       ac=a;
        System.out.println(a.getId_nv()); 
        if(a.getId_cv()==6){
            pnTaiSan.setLayout(new FlowLayout());
            pnNhanVien.setLayout(new FlowLayout());
            btNVChucVu.setVisible(false);
            btNVLuongCoBan.setVisible(false);
            btNVNhanVien.setVisible(false);
            btTSKhuVuc.setVisible(false);
            btTSLoaiThucUong.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        pnTaiSan = new javax.swing.JPanel();
        btTSKhuVuc = new javax.swing.JButton();
        btTSBan = new javax.swing.JButton();
        btTSLoaiThucUong = new javax.swing.JButton();
        btNVLuongCoBan = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbTop1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnNhanVien = new javax.swing.JPanel();
        btNVChucVu = new javax.swing.JButton();
        btNVNhanVien = new javax.swing.JButton();
        btNVThongKe = new javax.swing.JButton();
        btNVThuNhap = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbTop = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 3));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.BorderLayout());

        pnTaiSan.setLayout(new java.awt.GridLayout(1, 3));

        btTSKhuVuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btTSKhuVuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connection-06-26-64.png"))); // NOI18N
        btTSKhuVuc.setText("<html>Quản lý <br />khu vực</html>");
        btTSKhuVuc.setBorder(null);
        btTSKhuVuc.setBorderPainted(false);
        btTSKhuVuc.setFocusPainted(false);
        btTSKhuVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTSKhuVucActionPerformed(evt);
            }
        });
        pnTaiSan.add(btTSKhuVuc);

        btTSBan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btTSBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dining_Table-64.png"))); // NOI18N
        btTSBan.setText("<html>Quản lý <br />bàn</html>");
        btTSBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTSBanActionPerformed(evt);
            }
        });
        pnTaiSan.add(btTSBan);

        btTSLoaiThucUong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btTSLoaiThucUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cafe-64.png"))); // NOI18N
        btTSLoaiThucUong.setText("<html>Quản lý <br />loại thức uống</html>");
        btTSLoaiThucUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTSLoaiThucUongActionPerformed(evt);
            }
        });
        pnTaiSan.add(btTSLoaiThucUong);
        btTSLoaiThucUong.getAccessibleContext().setAccessibleDescription("");

        btNVLuongCoBan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNVLuongCoBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/04-64.png"))); // NOI18N
        btNVLuongCoBan.setText("<html>Quản lý <br /> lương cơ bản</html>");
        btNVLuongCoBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNVLuongCoBanActionPerformed(evt);
            }
        });
        pnTaiSan.add(btNVLuongCoBan);

        jPanel4.add(pnTaiSan, java.awt.BorderLayout.CENTER);

        lbTop1.setText("Quản lý tài sản ");
        jPanel6.add(lbTop1);

        jPanel4.add(jPanel6, java.awt.BorderLayout.NORTH);

        add(jPanel4);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnNhanVien.setLayout(new java.awt.GridLayout(1, 3));

        btNVChucVu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNVChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signing_contract-64.png"))); // NOI18N
        btNVChucVu.setText("<html>Quản lý <br />chức vụ</html>");
        btNVChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNVChucVuActionPerformed(evt);
            }
        });
        pnNhanVien.add(btNVChucVu);

        btNVNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNVNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/-23-64.png"))); // NOI18N
        btNVNhanVien.setText("<html>Quản lý <br />nhân viên</html>");
        btNVNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNVNhanVienActionPerformed(evt);
            }
        });
        pnNhanVien.add(btNVNhanVien);

        btNVThongKe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNVThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12-64.png"))); // NOI18N
        btNVThongKe.setText("<html>Thống kê</html>   ");
        btNVThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNVThongKeActionPerformed(evt);
            }
        });
        pnNhanVien.add(btNVThongKe);

        btNVThuNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNVThuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graph_money_growth-64.png"))); // NOI18N
        btNVThuNhap.setText("<html>Quản lý <br /> Thu nhập</html>");
        btNVThuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNVThuNhapActionPerformed(evt);
            }
        });
        pnNhanVien.add(btNVThuNhap);

        jPanel1.add(pnNhanVien, java.awt.BorderLayout.CENTER);

        lbTop.setText("Quản lý nhân viên");
        jPanel3.add(lbTop);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void btNVChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNVChucVuActionPerformed
        if(ac.getId_cv()==1){ 
        addPanel(new PnNVChucVu(), btNVChucVu);
        }
    }//GEN-LAST:event_btNVChucVuActionPerformed

    private void btNVLuongCoBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNVLuongCoBanActionPerformed
        // TODO add your handling code here:
        if(ac.getId_cv()==1){  
        addPanel(new PnNVLuongCoBan(), btNVLuongCoBan);
        }
    }//GEN-LAST:event_btNVLuongCoBanActionPerformed

    private void btNVNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNVNhanVienActionPerformed
        // TODO add your handling code here:
        if(ac.getId_cv()==1){  
        addPanel(new PnNVNhanVien(), btNVNhanVien);
       }
    }//GEN-LAST:event_btNVNhanVienActionPerformed

    private void btNVThuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNVThuNhapActionPerformed
        // TODO add your handling code here:
        addPanel(new PnNVThuNhap(), btNVThuNhap);
    }//GEN-LAST:event_btNVThuNhapActionPerformed

    private void btTSKhuVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTSKhuVucActionPerformed
        // TODO add your handling code here:
        if(ac.getId_cv()==1){  
        addPanel(new PnTSKhuVuc(), btTSKhuVuc);
        }
    }//GEN-LAST:event_btTSKhuVucActionPerformed

    private void btTSBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTSBanActionPerformed
        // TODO add your handling code here:
         addPanel(new PnTSBan(), btTSBan);
    }//GEN-LAST:event_btTSBanActionPerformed

    private void btTSLoaiThucUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTSLoaiThucUongActionPerformed
        // TODO add your handling code here:
        if(ac.getId_cv()==1){   
        addPanel(new PnTSLoaiThucUong(), btTSLoaiThucUong);
        }
    }//GEN-LAST:event_btTSLoaiThucUongActionPerformed

    private void btNVThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNVThongKeActionPerformed
        // TODO add your handling code here:
         addPanel(new PnNVThongKe(), btNVThongKe);
        
    }//GEN-LAST:event_btNVThongKeActionPerformed
     public void addPanel(JPanel pn ,JButton bt) {
        pnCenter.removeAll();
        pnCenter.add(pn, BorderLayout.CENTER);
       
        if(btRecently!=null && btRecently!=bt){
            btRecently.setForeground(Color.BLACK);
            btRecently=bt;
             btRecently.setForeground(Color.RED);
        }else if(btRecently==null){
             btRecently=bt;
             btRecently.setForeground(Color.RED);
        }
        
        pnCenter.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNVChucVu;
    private javax.swing.JButton btNVLuongCoBan;
    private javax.swing.JButton btNVNhanVien;
    private javax.swing.JButton btNVThongKe;
    private javax.swing.JButton btNVThuNhap;
    private javax.swing.JButton btTSBan;
    private javax.swing.JButton btTSKhuVuc;
    private javax.swing.JButton btTSLoaiThucUong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbTop;
    private javax.swing.JLabel lbTop1;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnTaiSan;
    // End of variables declaration//GEN-END:variables
}
