/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.inc;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Tran Van Son
 */
public class PnTopNV extends javax.swing.JPanel {
    private JButton btRecently=null;
    private PnCenter pnCenter;
    
    public PnTopNV(PnCenter pn,JButton bt) {
        initComponents();
        this.pnCenter=pn;
        btRecently=bt;
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btNVChucVu = new javax.swing.JButton();
        btNVLuongCoBan = new javax.swing.JButton();
        btNVNhanVien = new javax.swing.JButton();
        btNVThuNhap = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbTop = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        btNVChucVu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNVChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qluser.png"))); // NOI18N
        btNVChucVu.setText("<html>Quản lý <br />chức vụ</html>");
        btNVChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNVChucVuActionPerformed(evt);
            }
        });
        jPanel1.add(btNVChucVu);

        btNVLuongCoBan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNVLuongCoBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qluser.png"))); // NOI18N
        btNVLuongCoBan.setText("<html>Quản lý <br /> lương cơ bản</html>");
        btNVLuongCoBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNVLuongCoBanActionPerformed(evt);
            }
        });
        jPanel1.add(btNVLuongCoBan);

        btNVNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNVNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qluser.png"))); // NOI18N
        btNVNhanVien.setText("<html>Quản lý <br />nhân viên</html>");
        btNVNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNVNhanVienActionPerformed(evt);
            }
        });
        jPanel1.add(btNVNhanVien);

        btNVThuNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNVThuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qluser.png"))); // NOI18N
        btNVThuNhap.setText("<html>Quản lý <br /> Thu nhập</html>");
        btNVThuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNVThuNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btNVThuNhap);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        lbTop.setText("Quản lý nhân viên");
        jPanel2.add(lbTop);

        add(jPanel2, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btNVChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNVChucVuActionPerformed
    }//GEN-LAST:event_btNVChucVuActionPerformed

    private void btNVLuongCoBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNVLuongCoBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNVLuongCoBanActionPerformed

    private void btNVNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNVNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNVNhanVienActionPerformed

    private void btNVThuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNVThuNhapActionPerformed
        // TODO add your handling code here:
        addPanel(jPanel1, btNVThuNhap);
    }//GEN-LAST:event_btNVThuNhapActionPerformed
    
     public void addPanel(JPanel pn ,JButton bt) {
        pnCenter.removeAll();
        //pnCenter.add(pn, BorderLayout.CENTER);
       
        if(btRecently!=null && btRecently!=bt){
            btRecently.setForeground(Color.BLACK);
            btRecently=bt;
             btRecently.setForeground(Color.RED);
        }else if(btRecently==null){
             btRecently=bt;
             btRecently.setForeground(Color.RED);
        }
        
        pnCenter.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNVChucVu;
    private javax.swing.JButton btNVLuongCoBan;
    private javax.swing.JButton btNVNhanVien;
    private javax.swing.JButton btNVThuNhap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbTop;
    // End of variables declaration//GEN-END:variables
}
