/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view1;

import bean.HoaDon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hi
 */
public class FrThanhToan extends javax.swing.JPanel {
    public HoaDon hd;
    private DefaultTableModel model;
    private controller.ControllerThanhToan controllerThanhToan;
    /**
     * Creates new form FrThanhToan
     */
    public FrThanhToan(HoaDon hd) {
        initComponents();
        hd=hd;
        controllerThanhToan=new controller.ControllerThanhToan();
        model = new DefaultTableModel() {
       
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }


        };
        loadTable();
    }
    public void loadTable(){
        controllerThanhToan.loadTable(tbLTUHD,model,hd);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCatLeft = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfBanTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btThuNhapThanhToan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        spinThuNhapTimeVao = new javax.swing.JSpinner();
        cbThuNhapNhanVien = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tfKhuVucName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLTUHD = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        spinTongTien = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spinThuNhapTimeVao1 = new javax.swing.JSpinner();

        setLayout(new java.awt.BorderLayout());

        pnCatLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Hóa đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        pnCatLeft.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Bàn:");

        tfBanTen.setEnabled(false);
        tfBanTen.setPreferredSize(new java.awt.Dimension(6, 26));
        tfBanTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBanTenActionPerformed(evt);
            }
        });

        jLabel2.setText("Giờ vào:");

        btThuNhapThanhToan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btThuNhapThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btThuNhapThanhToan.setText("Thanh toán");
        btThuNhapThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThuNhapThanhToanActionPerformed(evt);
            }
        });
        jPanel4.add(btThuNhapThanhToan);

        jLabel7.setText("Nhân viên :");

        spinThuNhapTimeVao.setModel(new javax.swing.SpinnerDateModel());
        spinThuNhapTimeVao.setEditor(new javax.swing.JSpinner.DateEditor(spinThuNhapTimeVao, "dd/MM/yyyy hh:mm a"));

        cbThuNhapNhanVien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbThuNhapNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbThuNhapNhanVienActionPerformed(evt);
            }
        });

        jLabel4.setText("Khu vực:");

        tfKhuVucName.setEnabled(false);
        tfKhuVucName.setPreferredSize(new java.awt.Dimension(6, 26));
        tfKhuVucName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKhuVucNameActionPerformed(evt);
            }
        });

        tbLTUHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Tên", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbLTUHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbLTUHDMousePressed(evt);
            }
        });
        tbLTUHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbLTUHDKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbLTUHD);

        jLabel5.setText("Tổng tiền:");

        spinTongTien.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        spinTongTien.setEnabled(false);

        jLabel3.setText("Giờ ra:");

        spinThuNhapTimeVao1.setModel(new javax.swing.SpinnerDateModel());
        spinThuNhapTimeVao1.setEditor(new javax.swing.JSpinner.DateEditor(spinThuNhapTimeVao1, "dd/MM/yyyy hh:mm a"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinTongTien))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(12, 12, 12)
                                .addComponent(cbThuNhapNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(spinThuNhapTimeVao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinThuNhapTimeVao1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(43, 43, 43))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(22, 22, 22)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfBanTen, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfKhuVucName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfBanTen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfKhuVucName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinThuNhapTimeVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spinThuNhapTimeVao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbThuNhapNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pnCatLeft.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(pnCatLeft, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void tfBanTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBanTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBanTenActionPerformed

    private void cbThuNhapNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbThuNhapNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbThuNhapNhanVienActionPerformed

    private void tfKhuVucNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKhuVucNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKhuVucNameActionPerformed

    private void tbLTUHDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLTUHDMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbLTUHDMousePressed

    private void tbLTUHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbLTUHDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbLTUHDKeyReleased

    private void btThuNhapThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThuNhapThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btThuNhapThanhToanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btThuNhapThanhToan;
    private javax.swing.JComboBox cbThuNhapNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnCatLeft;
    private javax.swing.JSpinner spinThuNhapTimeVao;
    private javax.swing.JSpinner spinThuNhapTimeVao1;
    private javax.swing.JSpinner spinTongTien;
    private javax.swing.JTable tbLTUHD;
    private javax.swing.JTextField tfBanTen;
    private javax.swing.JTextField tfKhuVucName;
    // End of variables declaration//GEN-END:variables
}
