/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view1;

import bean.Account;
import bean.ChucVu;
import bean.NhanVien;
import controller.ControllerChucVu;
import controller.ControllerNhanVien;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Hi
 */
public class PnBottomCQ extends javax.swing.JPanel {
 private controller.ControllerNhanVien controllerNhanVien;
     private controller.ControllerChucVu controllerChucVu;
    private controller.ControllerAccount controllerAccount;
    private Account a;
    /**
     * Creates new form PnBottomTN
     */
    public PnBottomCQ(Account a) {
        initComponents();
          controllerAccount=new controller.ControllerAccount();
        controllerNhanVien=new ControllerNhanVien();
        controllerChucVu=new ControllerChucVu();
        setForm(a);
        this.a=a;
    }
      public void setForm(Account a){
        NhanVien nv=controllerNhanVien.getNhanViemByMaNV(a.getId_nv());
        ChucVu cv=controllerChucVu.getChucVuById(a.getId_cv());
        ArrayList<Account> alAccount=controllerAccount.getListAcc();
        for(Account ac:alAccount){
            System.out.println(ac.getId_cv());
            if(cv.getId_cv()!=ac.getId_cv()){
                pfPassWordTN.setText(ac.getPass());
            }else{
                pfPasswordCQ.setText(ac.getPass());
            }
        }  
        tfChucVu.setText(cv.getTen_cv());
        tfHoTen.setText(nv.getTen_nv());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        tfHoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfChucVu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pfPassWordTN = new javax.swing.JPasswordField();
        btBottom = new javax.swing.JButton();
        btBottomUpdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pfPasswordCQ = new javax.swing.JPasswordField();

        jLabel4.setText("Họ và tên :");

        tfHoTen.setEnabled(false);
        tfHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoTenActionPerformed(evt);
            }
        });

        jLabel5.setText("Chức vụ :");

        tfChucVu.setEnabled(false);
        tfChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChucVuActionPerformed(evt);
            }
        });

        jLabel6.setText("PasswordTN:");

        pfPassWordTN.setEnabled(false);
        pfPassWordTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPassWordTNActionPerformed(evt);
            }
        });

        btBottom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBottom.setForeground(java.awt.Color.green);
        btBottom.setText("V");
        btBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBottomActionPerformed(evt);
            }
        });

        btBottomUpdate.setText("Update");
        btBottomUpdate.setEnabled(false);
        btBottomUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBottomUpdateActionPerformed(evt);
            }
        });

        jLabel7.setText("PasswordCQ:");

        pfPasswordCQ.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pfPassWordTN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pfPasswordCQ, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBottomUpdate)
                .addGap(18, 18, 18)
                .addComponent(btBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(pfPassWordTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(pfPasswordCQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBottomUpdate)
                    .addComponent(btBottom)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChucVuActionPerformed

    private void btBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBottomActionPerformed
        // TODO add your handling code here:
          if ("X".equals(btBottom.getText())) {
            btBottom.setText("V");
            btBottom.setForeground(Color.GREEN);
            pfPassWordTN.setEnabled(false);
            pfPasswordCQ.setEnabled(false);
            btBottomUpdate.setEnabled(false);
        } else if ("V".equals(btBottom.getText())) {
            btBottom.setText("X");
            btBottom.setForeground(new Color(205, 0, 0));
            pfPassWordTN.setEnabled(true);
            pfPasswordCQ.setEnabled(true);
            btBottomUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_btBottomActionPerformed

    private void btBottomUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBottomUpdateActionPerformed
        // TODO add your handling code here:
         a.setPass(String.valueOf(pfPasswordCQ.getPassword()));
         System.out.println(a.getPass());
         Account a1=new Account(a.getId_cv(),String.valueOf(pfPassWordTN.getPassword()),0);
        if( controllerAccount.edit(a)>0&&controllerAccount.edit1(a1)>0){
            JOptionPane.showMessageDialog(null,"Sửa thành công");
            return;
        }
    }//GEN-LAST:event_btBottomUpdateActionPerformed

    private void pfPassWordTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPassWordTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPassWordTNActionPerformed

    private void tfHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoTenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBottom;
    private javax.swing.JButton btBottomUpdate;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pfPassWordTN;
    private javax.swing.JPasswordField pfPasswordCQ;
    private javax.swing.JTextField tfChucVu;
    private javax.swing.JTextField tfHoTen;
    // End of variables declaration//GEN-END:variables
}
