/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view1;

import bean.Account;
import bean.ChucVu;
import bean.NhanVien;
import controller.ControllerChucVu;
import controller.ControllerNhanVien;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Hi
 */
public class PnBottomTN extends javax.swing.JPanel {
private controller.ControllerNhanVien controllerNhanVien;
     private controller.ControllerChucVu controllerChucVu;
    private controller.ControllerAccount controllerAccount;
    private Account a;
    /**
     * Creates new form PnBottomTN
     */
    public PnBottomTN(Account a) {
        initComponents();
         controllerAccount=new controller.ControllerAccount();
        controllerNhanVien=new ControllerNhanVien();
        controllerChucVu=new ControllerChucVu();
        this.a=a;
        setForm(a);
    }
     public void setForm(Account a){
        NhanVien nv=controllerNhanVien.getNhanViemByMaNV(a.getId_nv());
        ChucVu cv=controllerChucVu.getChucVuById(a.getId_cv());
        System.out.println(cv +"fd"+ nv);
        tfChucVu.setText(cv.getTen_cv());
        tfHoTen.setText(nv.getTen_nv());
        pfPassWord.setText(a.getPass());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        tfHoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfChucVu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pfPassWord = new javax.swing.JPasswordField();
        btBottom = new javax.swing.JButton();
        btBottomUpdate = new javax.swing.JButton();

        jLabel4.setText("Họ và tên :");

        tfHoTen.setEnabled(false);

        jLabel5.setText("Chức vụ :");

        tfChucVu.setEnabled(false);
        tfChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChucVuActionPerformed(evt);
            }
        });

        jLabel6.setText("Password:");

        pfPassWord.setEnabled(false);

        btBottom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBottom.setForeground(java.awt.Color.green);
        btBottom.setText("V");
        btBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBottomActionPerformed(evt);
            }
        });

        btBottomUpdate.setText("Update");
        btBottomUpdate.setEnabled(false);
        btBottomUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBottomUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(pfPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btBottomUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfChucVu)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pfPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btBottomUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btBottom, btBottomUpdate, pfPassWord, tfChucVu, tfHoTen});

    }// </editor-fold>//GEN-END:initComponents

    private void tfChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChucVuActionPerformed

    private void btBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBottomActionPerformed
        // TODO add your handling code here:
          if ("X".equals(btBottom.getText())) {
            btBottom.setText("V");
            btBottom.setForeground(Color.GREEN);
            pfPassWord.setEnabled(false);
            btBottomUpdate.setEnabled(false);
        } else if ("V".equals(btBottom.getText())) {
            btBottom.setText("X");
            btBottom.setForeground(new Color(205, 0, 0));
            pfPassWord.setEnabled(true);
            btBottomUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_btBottomActionPerformed

    private void btBottomUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBottomUpdateActionPerformed
        // TODO add your handling code here:
         a.setPass(String.valueOf(pfPassWord.getPassword()));
         System.out.println(a.getPass());
        if( controllerAccount.edit(a)>0){
            JOptionPane.showMessageDialog(null,"Sửa thành công");
        }
    }//GEN-LAST:event_btBottomUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBottom;
    private javax.swing.JButton btBottomUpdate;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField pfPassWord;
    private javax.swing.JTextField tfChucVu;
    private javax.swing.JTextField tfHoTen;
    // End of variables declaration//GEN-END:variables
}
