/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view1;

import bean.Ban;
import bean.HoaDon;
import bean.KhuVuc;
import com.itextpdf.text.Document;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfDocument;
import controller.ControllerBan;
import controller.ControllerHoaDon;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import jxl.Workbook;
import jxl.biff.EmptyCell;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;
import library.LibraryDimension;
import library.LibraryPhieuHang;
import model.ModelKhuVucComboBox;
import model.ModelTrangThaiComboBox;

/**
 *
 * @author MinhHuyHo
 */
public class PnNVThongKe extends javax.swing.JPanel implements ActionListener {

    private DefaultTableModel model;
    private int crow;
    private int rowCount = 0;
    private String lKT = "";
    private controller.ControllerHoaDon controller;
    private Vector v;
    private  Document document;

    public PnNVThongKe() {
        initComponents();
        v = new Vector();

        btBanSearch.addActionListener(this);
        crow = -1;
        rowCount = tbHoaDon.getSelectedRowCount();
        controller = new ControllerHoaDon();
        //set split pane
        JSplitPane sp = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, pnCatLeft, pnCatRight);
        sp.setOneTouchExpandable(true);
        add(sp);
        pnCatLeft.setMinimumSize(new Dimension(LibraryDimension.PANEL_LEFT_WIDTH, pnCatLeft.getSize().height));
        model = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 5) {
                    return Double.class;
                }
                if (columnIndex == 0) {
                    return Integer.class;
                }
                return super.getColumnClass(columnIndex);
            }
        };
        loadTable(null, true);
        setTongTien();
        ((JComponent) tbHoaDon.getDefaultRenderer(Boolean.class)).setOpaque(true);

    }

    public void loadTable(HoaDon hd, boolean ctt) {
        controller.loadTable(tbHoaDon, model, hd, ctt);
    }

    public void setTongTien() {
        double sumMoney = 0;
        for (int i = 0; i < tbHoaDon.getRowCount(); i++) {
            sumMoney += (double) tbHoaDon.getValueAt(i,5 );
        }
        spinTongTien.setValue(sumMoney);
    }

    public void createExcel(String filename) throws IOException, WriteException {
        WritableWorkbook workBook = Workbook.createWorkbook(new File(filename));
        WritableSheet sheet = workBook.createSheet("Thống kê", 0);
        Vector<Vector> vGetDetail = getDetailTB(tbHoaDon);
        for (int i = 0; i < tbHoaDon.getColumnCount(); i++) {
            sheet.addCell(new Label(i, 0, tbHoaDon.getColumnName(i)));
            sheet.addCell(new EmptyCell(2, 2));
        }
        for (int i = 0; i < vGetDetail.size(); i++) {
            for (int j = 0; j < vGetDetail.get(i).size(); j++) {
                sheet.addCell(new jxl.write.Label(j, i + 1, String.valueOf(vGetDetail.get(i).get(j))));
            }
        }

        workBook.write();
        workBook.close();
    }

    public Vector<Vector> getDetailTB(JTable tbHoaDon) {
        Vector<Vector> vAll = new Vector<>();
        for (int i = 0; i < tbHoaDon.getRowCount(); i++) {
            Vector v = new Vector();
            for (int j = 0; j < tbHoaDon.getColumnCount(); j++) {

                v.add(tbHoaDon.getValueAt(i, j));
            }
            vAll.add(v);
        }
        return vAll;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCatLeft = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        spinDateFrom = new javax.swing.JSpinner();
        spinDateTo = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btBanSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnCatRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDon = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        spinTongTien = new javax.swing.JSpinner();

        setLayout(new java.awt.BorderLayout());

        pnCatLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thống kê", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        pnCatLeft.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        spinDateFrom.setModel(new javax.swing.SpinnerDateModel());
        spinDateFrom.setEditor(new javax.swing.JSpinner.DateEditor(spinDateFrom, "dd/MM/yyyy"));

        spinDateTo.setModel(new javax.swing.SpinnerDateModel());
        spinDateTo.setEditor(new javax.swing.JSpinner.DateEditor(spinDateTo, "dd/MM/yyyy "));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Đến ngày");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Từ ngày");

        btBanSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        btBanSearch.setText("Thống kê");
        btBanSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBanSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)
                        .addComponent(spinDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(spinDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btBanSearch)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {spinDateFrom, spinDateTo});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spinDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBanSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, spinDateFrom, spinDateTo});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnCatLeft.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/microsoft-excel-128.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        pnCatLeft.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(pnCatLeft, java.awt.BorderLayout.LINE_START);

        pnCatRight.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N

        tbHoaDon.setAutoCreateRowSorter(true);
        tbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbHoaDon.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbHoaDonMousePressed(evt);
            }
        });
        tbHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbHoaDonKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbHoaDon);

        jLabel3.setText("Tổng tiền :");

        spinTongTien.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        spinTongTien.setEnabled(false);

        javax.swing.GroupLayout pnCatRightLayout = new javax.swing.GroupLayout(pnCatRight);
        pnCatRight.setLayout(pnCatRightLayout);
        pnCatRightLayout.setHorizontalGroup(
            pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
            .addGroup(pnCatRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnCatRightLayout.setVerticalGroup(
            pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCatRightLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 109, Short.MAX_VALUE))
        );

        pnCatRightLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, spinTongTien});

        add(pnCatRight, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbHoaDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbHoaDonKeyReleased
        // TODO add your handling code here:
        setForm();
    }//GEN-LAST:event_tbHoaDonKeyReleased

    private void tbHoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonMousePressed
        // TODO add your handling code here:
        setForm();
    }//GEN-LAST:event_tbHoaDonMousePressed

    private void btBanSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBanSearchActionPerformed
        // TODO add your handling code here:
        HoaDon hd = new HoaDon();
        Date dTO = (Date) spinDateFrom.getValue();
        Date dFROM = (Date) spinDateTo.getValue();
        hd.setTimeRa(new Timestamp(dTO.getTime()));
        hd.setTimeVao(new Timestamp(dFROM.getTime()));
        loadTable(hd, true);
    }//GEN-LAST:event_btBanSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        FileNameExtensionFilter xmlFilter = new FileNameExtensionFilter("xls files (*.xls)", "xls");
        fc.addChoosableFileFilter(xmlFilter);
        fc.setFileFilter(xmlFilter);

        int ans = fc.showSaveDialog(null);
        if (ans == JFileChooser.APPROVE_OPTION) {
            SimpleDateFormat  sdf=new SimpleDateFormat("dd_MM_yyyy");
            String path = fc.getSelectedFile().getAbsolutePath() + File.separator + "KetQua"+sdf.format(new Date())+".xls";
            System.out.println(path);

            try {
                createExcel(path);
                JOptionPane.showMessageDialog(null,"Tạo file thành công");
            } catch (IOException ex) {
                Logger.getLogger(PnNVThongKe.class.getName()).log(Level.SEVERE, null, ex);
                  JOptionPane.showMessageDialog(null,"Tạo file thất bại");
            } catch (WriteException ex) {
                Logger.getLogger(PnNVThongKe.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Tạo file thất bại");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        FileNameExtensionFilter xmlFilter = new FileNameExtensionFilter("pdf files (*.pdf)", "pdf");
        fc.addChoosableFileFilter(xmlFilter);
        fc.setFileFilter(xmlFilter);

        int ans = fc.showSaveDialog(null);
        if (ans == JFileChooser.APPROVE_OPTION) {

            String path = fc.getSelectedFile().getAbsolutePath() + File.separator + "ThongKe.pdf";
		//Document document = new Document(PageSize.A4, 10, 10, 10, 10);
                Date dateTo=(Date) spinDateTo.getValue();
                Date dateFROM=(Date) spinDateFrom.getValue();
                document=new Document(PageSize.A4, 10, 10, 10, 10);
                if(controller.createPhieuMua(document,path,dateTo,dateFROM)>0){
                    JOptionPane.showMessageDialog(null,"Đã xuất file thành công");
                }else{
                    JOptionPane.showMessageDialog(null,"Trùng tên với một file có sẵn");
                }

        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    public void setForm() {

    }

    public void resetForm() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBanSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnCatLeft;
    private javax.swing.JPanel pnCatRight;
    private javax.swing.JSpinner spinDateFrom;
    private javax.swing.JSpinner spinDateTo;
    private javax.swing.JSpinner spinTongTien;
    private javax.swing.JTable tbHoaDon;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

    }
  
    
}
