/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view1;

import bean.ChucVu;
import bean.LoaiThucUong;
import bean.LuongCoBan;
import bean.NhanVien;
import controller.ControllerLoaiThucUong;
import controller.ControllerNhanVien;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JSplitPane;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import library.LibraryDimension;
import model.ModelChucVuComboBox;
import model.ModelLuongComboBox;
import renderer.TableCellRendererHeaderColumn;

/**
 *
 * @author Tran Van Son
 */
public class PnNVNhanVien extends javax.swing.JPanel implements ActionListener {

    private DefaultTableModel model;
    private int crow;
    private int rowCount = 0;
    private controller.ControllerNhanVien controller;

    /**
     * Creates new form PnCat
     */
    public PnNVNhanVien() {
        initComponents();
        btNhanVienNgayActiveFind.addActionListener(this);
        btNhanVienNhapLaiFind.addActionListener(this);
        btNhanVienTimKiemFind.addActionListener(this);
        btNhanVienNhapLai.addActionListener(this);
        btNhanVienSua.addActionListener(this);
        btNhanVienTTActive.addActionListener(this);
        btNhanVienThem.addActionListener(this);
        btNhanVienXoa.addActionListener(this);
        btNhanVienNgayActiveFind.addActionListener(this);
        btNhanVienTTActiveFind.addActionListener(this);

        crow = -1;
        rowCount = 0;
        controller = new ControllerNhanVien();
        //set split pane
        JSplitPane sp = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, pnCatLeft, pnCatRight);
        sp.setOneTouchExpandable(true);
        add(sp);
        model = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) {
                    return Integer.class;
                }
                if (columnIndex == 6) {
                    return Boolean.class;
                }

                return super.getColumnClass(columnIndex);
            }

        };
        loadTable(null, false, false);
        loadCombo(null, null, 0);
        loadCombo(null, null, 1);
        ((JComponent) tbNhanVien.getDefaultRenderer(Boolean.class)).setOpaque(true);
    }

    public void loadTable(NhanVien nv, boolean ctt, boolean cn) {
        controller.loadTable(tbNhanVien, model, nv, ctt, cn);
    }

    public void loadCombo(ChucVu cv, LuongCoBan lcb, int ck) {
        if (ck == 0) {
            cbNhanVienChucVu.setModel(new ModelChucVuComboBox(cv));
            cbNhanVienLevel.setModel(new ModelLuongComboBox(lcb));
        } else {
            cbNhanVienChucVuFind.setModel(new ModelChucVuComboBox(cv));
            cbNhanVienLevelFind.setModel(new ModelLuongComboBox(lcb));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCatLeft = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNhanVienId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btNhanVienThem = new javax.swing.JButton();
        btNhanVienSua = new javax.swing.JButton();
        btNhanVienNhapLai = new javax.swing.JButton();
        btNhanVienXoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbNhanVienLevel = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        spinNhanVienNgaySinh = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbNhanVienChucVu = new javax.swing.JComboBox();
        tfNhanVienName = new javax.swing.JTextField();
        tfNhanVienDiaChi = new javax.swing.JTextField();
        tfNhanVienSDT = new javax.swing.JTextField();
        tfNhanVienEmail = new javax.swing.JTextField();
        spinNhanVienNgayVao = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        spinNhanVienNgayRa = new javax.swing.JSpinner();
        ckbActive = new javax.swing.JCheckBox();
        btNhanVienTTActive = new javax.swing.JButton();
        pnCatRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfNhanVienIdFind = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfNhanVienNameFind = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbNhanVienChucVuFind = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        cbNhanVienLevelFind = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        spinNhanVienNgayVaoFind = new javax.swing.JSpinner();
        spinNhanVienNgayRaFind = new javax.swing.JSpinner();
        btNhanVienNgayActiveFind = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ckbActiveFind = new javax.swing.JCheckBox();
        btNhanVienTTActiveFind = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btNhanVienTimKiemFind = new javax.swing.JButton();
        btNhanVienNhapLaiFind = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnCatLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Form chức năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        pnCatLeft.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("CMND:");

        tfNhanVienId.setPreferredSize(new java.awt.Dimension(6, 26));

        jLabel2.setText("Tên nhân viên:");

        btNhanVienThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhanVienThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btNhanVienThem.setText("Thêm");
        jPanel3.add(btNhanVienThem);

        btNhanVienSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhanVienSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btNhanVienSua.setText("Sửa");
        btNhanVienSua.setPreferredSize(new java.awt.Dimension(85, 25));
        jPanel3.add(btNhanVienSua);

        btNhanVienNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhanVienNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btNhanVienNhapLai.setText("Nhập lại");
        btNhanVienNhapLai.setPreferredSize(new java.awt.Dimension(95, 25));
        btNhanVienNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanVienNhapLaiActionPerformed(evt);
            }
        });
        jPanel3.add(btNhanVienNhapLai);

        btNhanVienXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhanVienXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.gif"))); // NOI18N
        btNhanVienXoa.setText("Xóa");
        btNhanVienXoa.setPreferredSize(new java.awt.Dimension(85, 25));
        jPanel3.add(btNhanVienXoa);

        jLabel5.setText("Ngày sinh:");

        jLabel6.setText("Email:");

        jLabel8.setText("Chức vụ:");

        cbNhanVienLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbNhanVienLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhanVienLevelActionPerformed(evt);
            }
        });

        jLabel9.setText("Ngày vào :");

        spinNhanVienNgaySinh.setModel(new javax.swing.SpinnerDateModel());
        spinNhanVienNgaySinh.setEditor(new javax.swing.JSpinner.DateEditor(spinNhanVienNgaySinh, "dd/MM/yyyy "));

        jLabel14.setText("Địa chỉ :");

        jLabel15.setText("SĐT: ");

        jLabel16.setText("Level:");

        cbNhanVienChucVu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbNhanVienChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhanVienChucVuActionPerformed(evt);
            }
        });

        tfNhanVienName.setPreferredSize(new java.awt.Dimension(6, 32));
        tfNhanVienName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNhanVienNameActionPerformed(evt);
            }
        });

        tfNhanVienDiaChi.setPreferredSize(new java.awt.Dimension(6, 32));

        tfNhanVienSDT.setPreferredSize(new java.awt.Dimension(6, 32));
        tfNhanVienSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNhanVienSDTActionPerformed(evt);
            }
        });

        tfNhanVienEmail.setPreferredSize(new java.awt.Dimension(6, 32));
        tfNhanVienEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNhanVienEmailActionPerformed(evt);
            }
        });

        spinNhanVienNgayVao.setModel(new javax.swing.SpinnerDateModel());
        spinNhanVienNgayVao.setEditor(new javax.swing.JSpinner.DateEditor(spinNhanVienNgayVao, "dd/MM/yyyy "));

        jLabel17.setText("Ngày ra:");

        spinNhanVienNgayRa.setModel(new javax.swing.SpinnerDateModel());
        spinNhanVienNgayRa.setEditor(new javax.swing.JSpinner.DateEditor(spinNhanVienNgayRa, "dd/MM/yyyy"));
        spinNhanVienNgayRa.setEnabled(false);

        ckbActive.setText("active");
        ckbActive.setEnabled(false);
        ckbActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbActiveActionPerformed(evt);
            }
        });

        btNhanVienTTActive.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhanVienTTActive.setForeground(new java.awt.Color(51, 102, 0));
        btNhanVienTTActive.setText("V");
        btNhanVienTTActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanVienTTActiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckbActive)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btNhanVienTTActive))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spinNhanVienNgayVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(spinNhanVienNgayRa))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNhanVienDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNhanVienName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinNhanVienNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNhanVienId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 165, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(49, 49, 49)
                        .addComponent(tfNhanVienSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(48, 48, 48)
                        .addComponent(tfNhanVienEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel16))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNhanVienLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNhanVienChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNhanVienId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNhanVienName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinNhanVienNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNhanVienDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfNhanVienSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNhanVienEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbNhanVienChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbNhanVienLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(spinNhanVienNgayVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinNhanVienNgayRa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbActive)
                        .addGap(5, 5, 5))
                    .addComponent(btNhanVienTTActive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btNhanVienTTActive, cbNhanVienChucVu, cbNhanVienLevel, spinNhanVienNgayRa, spinNhanVienNgayVao, tfNhanVienEmail, tfNhanVienId});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {spinNhanVienNgaySinh, tfNhanVienName});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfNhanVienDiaChi, tfNhanVienSDT});

        pnCatLeft.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(pnCatLeft, java.awt.BorderLayout.LINE_START);

        pnCatRight.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        pnCatRight.setLayout(new java.awt.BorderLayout());

        tbNhanVien.setAutoCreateRowSorter(true);
        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tbNhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbNhanVienMousePressed(evt);
            }
        });
        tbNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbNhanVienKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhanVien);

        pnCatRight.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("ID:");

        tfNhanVienIdFind.setPreferredSize(new java.awt.Dimension(6, 32));

        jLabel10.setText("Tên:");

        jLabel11.setText("Chức vụ:");

        cbNhanVienChucVuFind.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setText("Level:");

        cbNhanVienLevelFind.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Ngày vào:");

        spinNhanVienNgayVaoFind.setModel(new javax.swing.SpinnerDateModel());
        spinNhanVienNgayVaoFind.setEditor(new javax.swing.JSpinner.DateEditor(spinNhanVienNgayVaoFind, "dd/MM/yyyy"));
        spinNhanVienNgayVaoFind.setEnabled(false);

        spinNhanVienNgayRaFind.setModel(new javax.swing.SpinnerDateModel());
        spinNhanVienNgayRaFind.setEditor(new javax.swing.JSpinner.DateEditor(spinNhanVienNgayRaFind, "dd/MM/yyyy"));
        spinNhanVienNgayRaFind.setEnabled(false);

        btNhanVienNgayActiveFind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhanVienNgayActiveFind.setForeground(new java.awt.Color(51, 102, 0));
        btNhanVienNgayActiveFind.setText("V");
        btNhanVienNgayActiveFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanVienNgayActiveFindActionPerformed(evt);
            }
        });

        jLabel13.setText("Đến");

        ckbActiveFind.setText("Active");
        ckbActiveFind.setEnabled(false);
        ckbActiveFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbActiveFindActionPerformed(evt);
            }
        });

        btNhanVienTTActiveFind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhanVienTTActiveFind.setForeground(new java.awt.Color(51, 102, 0));
        btNhanVienTTActiveFind.setText("V");
        btNhanVienTTActiveFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanVienTTActiveFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tfNhanVienIdFind, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNhanVienNameFind))
                            .addComponent(cbNhanVienChucVuFind, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(37, 37, 37)
                        .addComponent(cbNhanVienLevelFind, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ckbActiveFind)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btNhanVienTTActiveFind))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(spinNhanVienNgayVaoFind, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinNhanVienNgayRaFind, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(btNhanVienNgayActiveFind)))))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btNhanVienNgayActiveFind, btNhanVienTTActiveFind});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNhanVienIdFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfNhanVienNameFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbNhanVienChucVuFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbNhanVienLevelFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spinNhanVienNgayVaoFind, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinNhanVienNgayRaFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btNhanVienNgayActiveFind))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbActiveFind)
                    .addComponent(btNhanVienTTActiveFind, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btNhanVienNgayActiveFind, btNhanVienTTActiveFind, cbNhanVienChucVuFind, cbNhanVienLevelFind, spinNhanVienNgayRaFind, spinNhanVienNgayVaoFind, tfNhanVienIdFind, tfNhanVienNameFind});

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel5.setLayout(new java.awt.GridLayout(2, 1, 0, 8));

        btNhanVienTimKiemFind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhanVienTimKiemFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        btNhanVienTimKiemFind.setText("Tìm kiếm");
        btNhanVienTimKiemFind.setPreferredSize(new java.awt.Dimension(130, 23));
        btNhanVienTimKiemFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanVienTimKiemFindActionPerformed(evt);
            }
        });
        jPanel5.add(btNhanVienTimKiemFind);

        btNhanVienNhapLaiFind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhanVienNhapLaiFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btNhanVienNhapLaiFind.setText("Nhập lại");
        btNhanVienNhapLaiFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanVienNhapLaiFindActionPerformed(evt);
            }
        });
        jPanel5.add(btNhanVienNhapLaiFind);

        jPanel2.add(jPanel5, java.awt.BorderLayout.EAST);

        pnCatRight.add(jPanel2, java.awt.BorderLayout.NORTH);

        add(pnCatRight, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btNhanVienTimKiemFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanVienTimKiemFindActionPerformed
        // TODO add your handling code here:
        boolean ckTT = false;
        boolean ckN = false;
        int cmnd = -1;
        if (!"".equals(tfNhanVienIdFind.getText())) {
            try {
                cmnd = Integer.parseInt(tfNhanVienIdFind.getText());
                System.out.println(cmnd);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Hãy nhập vào số CMND của bạn");
            }
        }
        java.sql.Date ngayRa = null;
        java.sql.Date ngayVao = null;
        if ("X".equals(btNhanVienNgayActiveFind.getText())) {
            ckN = true;
            Date date1 = (Date) spinNhanVienNgayVaoFind.getValue();
            ngayVao = new java.sql.Date(date1.getTime());

        }
        if (spinNhanVienNgayRaFind.isEnabled()) {
            Date date2 = (Date) spinNhanVienNgayVaoFind.getValue();
            ngayRa = new java.sql.Date(date2.getTime());
        }
        if ("X".equals(btNhanVienTTActiveFind.getText())) {
            ckTT = true;
        }

        NhanVien nv = new NhanVien(cmnd, tfNhanVienName.getText(), new java.sql.Date(cmnd), "", "", "", ((LuongCoBan) cbNhanVienLevelFind.getSelectedItem()).getLevel_lcb(), ((ChucVu) cbNhanVienChucVuFind.getSelectedItem()).getId_cv(), ngayVao, ngayRa, ckbActiveFind.isSelected());
        loadTable(nv, ckTT, ckN);
    }//GEN-LAST:event_btNhanVienTimKiemFindActionPerformed

    private void tbNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMousePressed
        // TODO add your handling code here:
        setForm();
    }//GEN-LAST:event_tbNhanVienMousePressed

    private void tbNhanVienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbNhanVienKeyReleased
        // TODO add your handling code here:
        setForm();
    }//GEN-LAST:event_tbNhanVienKeyReleased

    private void tfNhanVienEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNhanVienEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNhanVienEmailActionPerformed

    private void tfNhanVienNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNhanVienNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNhanVienNameActionPerformed

    private void cbNhanVienChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNhanVienChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNhanVienChucVuActionPerformed

    private void cbNhanVienLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNhanVienLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNhanVienLevelActionPerformed

    private void btNhanVienNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanVienNhapLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNhanVienNhapLaiActionPerformed

    private void btNhanVienNgayActiveFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanVienNgayActiveFindActionPerformed
        // TODO add your handling code here:
        if ("X".equals(btNhanVienNgayActiveFind.getText())) {
            btNhanVienNgayActiveFind.setText("V");
            btNhanVienNgayActiveFind.setForeground(Color.GREEN);
            spinNhanVienNgayVaoFind.setEnabled(false);
            spinNhanVienNgayRaFind.setEnabled(false);
        } else if ("V".equals(btNhanVienNgayActiveFind.getText())) {
            btNhanVienNgayActiveFind.setText("X");
            btNhanVienNgayActiveFind.setForeground(new Color(205, 0, 0));
            spinNhanVienNgayVaoFind.setEnabled(true);
            if ("X".equals(btNhanVienTTActiveFind.getText()) && !ckbActiveFind.isSelected()) {
                System.out.println("111");
                spinNhanVienNgayRaFind.setEnabled(true);
            }
            //   
        }


    }//GEN-LAST:event_btNhanVienNgayActiveFindActionPerformed

    private void tfNhanVienSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNhanVienSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNhanVienSDTActionPerformed

    private void btNhanVienNhapLaiFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanVienNhapLaiFindActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btNhanVienNhapLaiFindActionPerformed

    private void ckbActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbActiveActionPerformed
        // TODO add your handling code here:
        if (!ckbActive.isSelected()) {
            spinNhanVienNgayRa.setEnabled(true);
        } else {
            spinNhanVienNgayRa.setEnabled(false);
        }

    }//GEN-LAST:event_ckbActiveActionPerformed

    private void btNhanVienTTActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanVienTTActiveActionPerformed
        // TODO add your handling code here:
        if ("X".equals(btNhanVienTTActive.getText())) {
            btNhanVienTTActive.setText("V");
            btNhanVienTTActive.setForeground(Color.GREEN);
            ckbActive.setEnabled(false);
        } else if ("V".equals(btNhanVienTTActive.getText())) {
            btNhanVienTTActive.setText("X");
            btNhanVienTTActive.setForeground(new Color(205, 0, 0));
            ckbActive.setEnabled(true);
        }
    }//GEN-LAST:event_btNhanVienTTActiveActionPerformed

    private void ckbActiveFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbActiveFindActionPerformed
        // TODO add your handling code here:
        if (!ckbActiveFind.isSelected()) {
            if ("X".equals(btNhanVienNgayActiveFind.getText())) {
                System.out.println("ngay");
                spinNhanVienNgayRaFind.setEnabled(true);
            } else if ("V".equals(btNhanVienNgayActiveFind.getText())) {
                spinNhanVienNgayRaFind.setEnabled(false);
            }

        } else if (ckbActiveFind.isSelected()) {
            spinNhanVienNgayRaFind.setEnabled(false);
        }

    }//GEN-LAST:event_ckbActiveFindActionPerformed

    private void btNhanVienTTActiveFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanVienTTActiveFindActionPerformed
        // TODO add your handling code here:

        if ("X".equals(btNhanVienTTActiveFind.getText())) {
            btNhanVienTTActiveFind.setText("V");
            btNhanVienTTActiveFind.setForeground(Color.GREEN);
            ckbActiveFind.setEnabled(false);
            spinNhanVienNgayRaFind.setEnabled(false);
        } else if ("V".equals(btNhanVienTTActiveFind.getText())) {

            btNhanVienTTActiveFind.setText("X");
            btNhanVienTTActiveFind.setForeground(new Color(205, 0, 0));
            ckbActiveFind.setEnabled(true);
            if ("X".equals(btNhanVienNgayActiveFind.getText()) && !ckbActiveFind.isSelected()) {
                spinNhanVienNgayRaFind.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btNhanVienTTActiveFindActionPerformed
    public void setForm() {
        crow = tbNhanVien.getSelectedRow();

        NhanVien nv = controller.getNhanViemByMaNV((int) tbNhanVien.getValueAt(crow, 0));
        tfNhanVienId.setText(String.valueOf(nv.getMa_nv()));
        tfNhanVienName.setText(nv.getTen_nv());
        spinNhanVienNgaySinh.setValue(nv.getNgaySinh_nv());
        tfNhanVienDiaChi.setText(nv.getDiaChi_nv());
        tfNhanVienSDT.setText(nv.getSdt_nv());
        tfNhanVienEmail.setText(nv.getEmail_nv());
        loadCombo((ChucVu) tbNhanVien.getValueAt(crow, 4), (LuongCoBan) tbNhanVien.getValueAt(crow, 5), 0);
        spinNhanVienNgayVao.setValue(nv.getNgayVao_nv());
        ckbActive.setSelected(nv.isTrangThai_nv());
        btNhanVienTTActive.setText("V");
        btNhanVienTTActive.setForeground(Color.GREEN);
        ckbActive.setEnabled(false);
        if (!nv.isTrangThai_nv()) {
            spinNhanVienNgayRa.setEnabled(false);
            spinNhanVienNgayRa.setValue(nv.getNgayRa_nv());
        } else {
            spinNhanVienNgayRa.setEnabled(false);
        }
        tfNhanVienIdFind.setText("");
        tfNhanVienNameFind.setText("");
        spinNhanVienNgayRaFind.setValue(new Date());
        spinNhanVienNgayVaoFind.setValue(new Date());

    }

    public void resetForm() {
        tfNhanVienId.setText("");
        tfNhanVienName.setText("");
        spinNhanVienNgaySinh.setValue(new Date());
        tfNhanVienDiaChi.setText("");
        tfNhanVienSDT.setText("");
        tfNhanVienEmail.setText("");
        loadCombo(null, null, 0);
        spinNhanVienNgayVao.setValue(new Date());
        spinNhanVienNgayRa.setValue(new Date());
        spinNhanVienNgayRa.setEnabled(false);
        ckbActive.setSelected(false);
        btNhanVienTTActive.setText("V");
        btNhanVienTTActive.setForeground(Color.GREEN);
        ckbActive.setEnabled(false);
        tfNhanVienIdFind.setText("");
        tfNhanVienNameFind.setText("");
        spinNhanVienNgayRaFind.setValue(new Date());
        spinNhanVienNgayVaoFind.setValue(new Date());
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNhanVienNgayActiveFind;
    private javax.swing.JButton btNhanVienNhapLai;
    private javax.swing.JButton btNhanVienNhapLaiFind;
    private javax.swing.JButton btNhanVienSua;
    private javax.swing.JButton btNhanVienTTActive;
    private javax.swing.JButton btNhanVienTTActiveFind;
    private javax.swing.JButton btNhanVienThem;
    private javax.swing.JButton btNhanVienTimKiemFind;
    private javax.swing.JButton btNhanVienXoa;
    private javax.swing.JComboBox cbNhanVienChucVu;
    private javax.swing.JComboBox cbNhanVienChucVuFind;
    private javax.swing.JComboBox cbNhanVienLevel;
    private javax.swing.JComboBox cbNhanVienLevelFind;
    private javax.swing.JCheckBox ckbActive;
    private javax.swing.JCheckBox ckbActiveFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnCatLeft;
    private javax.swing.JPanel pnCatRight;
    private javax.swing.JSpinner spinNhanVienNgayRa;
    private javax.swing.JSpinner spinNhanVienNgayRaFind;
    private javax.swing.JSpinner spinNhanVienNgaySinh;
    private javax.swing.JSpinner spinNhanVienNgayVao;
    private javax.swing.JSpinner spinNhanVienNgayVaoFind;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTextField tfNhanVienDiaChi;
    private javax.swing.JTextField tfNhanVienEmail;
    private javax.swing.JTextField tfNhanVienId;
    private javax.swing.JTextField tfNhanVienIdFind;
    private javax.swing.JTextField tfNhanVienName;
    private javax.swing.JTextField tfNhanVienNameFind;
    private javax.swing.JTextField tfNhanVienSDT;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btNhanVienThem) {
            int cmnd = -1;
            try {
                cmnd = Integer.parseInt(tfNhanVienId.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Hãy nhập vào số CMND của bạn");
            }
            Date date = (Date) spinNhanVienNgaySinh.getValue();
            java.sql.Date d = new java.sql.Date(date.getTime());
            Date date1 = (Date) spinNhanVienNgayVao.getValue();
            java.sql.Date d1 = new java.sql.Date(date1.getTime());
            java.sql.Date ngayRa = null;
            if (!ckbActive.isSelected()) {
                Date date2 = (Date) spinNhanVienNgayRa.getValue();
                ngayRa = new java.sql.Date(date2.getTime());
            }
            NhanVien nv = new NhanVien(cmnd, tfNhanVienName.getText(), d, tfNhanVienDiaChi.getText(), tfNhanVienSDT.getText(), tfNhanVienEmail.getText(), ((LuongCoBan) cbNhanVienLevel.getSelectedItem()).getLevel_lcb(), ((ChucVu) cbNhanVienChucVu.getSelectedItem()).getId_cv(), d1, ngayRa, true);
            if (controller.add(nv) > 0) {
                System.out.println(rowCount);
                rowCount = tbNhanVien.getRowCount();
                loadTable(null, false, false);
                tbNhanVien.setRowSelectionInterval(rowCount - 1, rowCount - 1);
                resetForm();
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                return;
            }
        }
        if (e.getSource() == btNhanVienNhapLai) {
            resetForm();
        }
        if (e.getSource() == btNhanVienXoa) {
            int cmnd = -1;
            try {
                cmnd = Integer.parseInt(tfNhanVienId.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Hãy chọn hoặc nhập CMND để xóa");
            }
            NhanVien nv = new NhanVien(cmnd, TOOL_TIP_TEXT_KEY, null, TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY, cmnd, cmnd, null, null, true);
            if (controller.delete(nv) > 0) {

                loadTable(null, false, false);
                resetForm();
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                return;
            }
        }
        if (e.getSource() == btNhanVienSua) {
            crow = tbNhanVien.getSelectedRow();
            int ccmnd = (int) tbNhanVien.getValueAt(crow, 0);
            int cmnd = -1;
            try {
                cmnd = Integer.parseInt(tfNhanVienId.getText());
                System.out.println(cmnd);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Hãy nhập vào số CMND của bạn");
            }
            Date date = (Date) spinNhanVienNgaySinh.getValue();
            java.sql.Date d = new java.sql.Date(date.getTime());
            Date date1 = (Date) spinNhanVienNgayVao.getValue();
            java.sql.Date d1 = new java.sql.Date(date1.getTime());
            java.sql.Date ngayRa = null;
            if (!ckbActive.isSelected()) {
                Date date2 = (Date) spinNhanVienNgayRa.getValue();
                ngayRa = new java.sql.Date(date2.getTime());
            }
            NhanVien nv = new NhanVien(cmnd, tfNhanVienName.getText(), d, tfNhanVienDiaChi.getText(), tfNhanVienSDT.getText(), tfNhanVienEmail.getText(), ((LuongCoBan) cbNhanVienLevel.getSelectedItem()).getLevel_lcb(), ((ChucVu) cbNhanVienChucVu.getSelectedItem()).getId_cv(), d1, ngayRa, ckbActive.isSelected());
            if (controller.edit(nv, ccmnd) > 0) {
                loadTable(null, false, false);
                tbNhanVien.setRowSelectionInterval(crow, crow);
                resetForm();
                JOptionPane.showMessageDialog(null, "Sửa thành công");
                return;
            }
        }
//        if(e.getSource()==btLTUXoa){
//            int id=0;
//            if(!"".equals(tfLTUId.getText())){
//                    id=Integer.parseInt(tfLTUId.getText());
//            }
//            
//                LoaiThucUong ltu=new LoaiThucUong(id,null,0,0,"","");
//                if(controller.delete(ltu)>0){
//                 rowCount=tbLoaiThucUong.getRowCount();
//                    loadTable(null);
//          tbLoaiThucUong.setRowSelectionInterval(rowCount,rowCount);
//          JOptionPane.showMessageDialog(null,"Thêm thành công");
//          return;
//                }  
//        }
    }
}
