/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view1;

import bean.LuongCoBan;
import controller.ControllerLuongCoBan;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import library.LibraryDimension;

/**
 *
 * @author MinhHuyHo
 */
public class PnNVLuongCoBan extends javax.swing.JPanel implements ActionListener {

    private DefaultTableModel model;
    private int crow;
    private int rowCount = 0;
    private String lKT = "";
    private controller.ControllerLuongCoBan controller;

    public PnNVLuongCoBan() {
        initComponents();
      btUserNhapLai.addActionListener(this);
        btUserSearch.addActionListener(this);
        btUserSua.addActionListener(this);
        btUserThem.addActionListener(this);
        btUserXoa.addActionListener(this);
        crow=-1;
        rowCount=tbUser.getSelectedRowCount();
        controller=new ControllerLuongCoBan();
        //set split pane
        JSplitPane sp = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, pnCatLeft, pnCatRight);
        sp.setOneTouchExpandable(true);
        add(sp);
        pnCatLeft.setMinimumSize(new Dimension(LibraryDimension.PANEL_LEFT_WIDTH, pnCatLeft.getSize().height));
        model = new DefaultTableModel() {
       
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 1) {
                    return Double.class;
                }
                return super.getColumnClass(columnIndex);
            }

        };
        loadTable( null);
     ( (JComponent)  tbUser.getDefaultRenderer(Boolean.class)).setOpaque(true);

    }

    public void loadTable(LuongCoBan lcb) {
        controller.loadTable(tbUser, model,lcb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCatLeft = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfUserId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btUserThem = new javax.swing.JButton();
        btUserSua = new javax.swing.JButton();
        btUserNhapLai = new javax.swing.JButton();
        btUserXoa = new javax.swing.JButton();
        spinLCBLuong = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfUserIdFind = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btUserSearch = new javax.swing.JButton();
        spinLCBLuongFind = new javax.swing.JSpinner();
        pnCatRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUser = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnCatLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Form chức năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        pnCatLeft.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Level  :");

        tfUserId.setEnabled(false);
        tfUserId.setPreferredSize(new java.awt.Dimension(6, 32));

        jLabel2.setText("Lương :");

        btUserThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btUserThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btUserThem.setText("Thêm");
        jPanel3.add(btUserThem);

        btUserSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btUserSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btUserSua.setText("Sửa");
        btUserSua.setPreferredSize(new java.awt.Dimension(85, 25));
        jPanel3.add(btUserSua);

        btUserNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btUserNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btUserNhapLai.setText("Nhập lại");
        btUserNhapLai.setPreferredSize(new java.awt.Dimension(95, 25));
        btUserNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserNhapLaiActionPerformed(evt);
            }
        });
        jPanel3.add(btUserNhapLai);

        btUserXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btUserXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.gif"))); // NOI18N
        btUserXoa.setText("Xóa");
        btUserXoa.setPreferredSize(new java.awt.Dimension(85, 25));
        jPanel3.add(btUserXoa);

        spinLCBLuong.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUserId, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(spinLCBLuong))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {spinLCBLuong, tfUserId});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinLCBLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {spinLCBLuong, tfUserId});

        pnCatLeft.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel3.setText("Level :");

        tfUserIdFind.setPreferredSize(new java.awt.Dimension(6, 32));

        jLabel4.setText("Lương :");

        btUserSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        btUserSearch.setText("Tìm kiếm");
        jPanel5.add(btUserSearch);

        spinLCBLuongFind.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUserIdFind, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(spinLCBLuongFind))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {spinLCBLuongFind, tfUserIdFind});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfUserIdFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinLCBLuongFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {spinLCBLuongFind, tfUserIdFind});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnCatLeft.add(jPanel2, java.awt.BorderLayout.SOUTH);

        add(pnCatLeft, java.awt.BorderLayout.LINE_START);

        pnCatRight.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N

        tbUser.setAutoCreateRowSorter(true);
        tbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbUser.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbUserMousePressed(evt);
            }
        });
        tbUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbUserKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbUser);

        javax.swing.GroupLayout pnCatRightLayout = new javax.swing.GroupLayout(pnCatRight);
        pnCatRight.setLayout(pnCatRightLayout);
        pnCatRightLayout.setHorizontalGroup(
            pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCatRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCatRightLayout.setVerticalGroup(
            pnCatRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCatRightLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnCatRight, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbUserKeyReleased
        // TODO add your handling code here:
        setForm();
    }//GEN-LAST:event_tbUserKeyReleased

    private void tbUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUserMousePressed
        // TODO add your handling code here:
        setForm();
    }//GEN-LAST:event_tbUserMousePressed

    private void btUserNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserNhapLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btUserNhapLaiActionPerformed
     public void setForm() {
        crow=tbUser.getSelectedRow();
        tfUserId.setText(tbUser.getValueAt(crow, 0).toString());
        spinLCBLuong.setValue(Double.parseDouble(tbUser.getValueAt(crow,1).toString()));
    }

    public void resetForm() {
      tfUserId.setText("");
      spinLCBLuong.setValue(0);
      tbUser.clearSelection();
    }
    public double checkDouble(String d){
        double st=0;
        try{
        st=Double.parseDouble(d);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập vào số");
        }
        return st;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btUserNhapLai;
    private javax.swing.JButton btUserSearch;
    private javax.swing.JButton btUserSua;
    private javax.swing.JButton btUserThem;
    private javax.swing.JButton btUserXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnCatLeft;
    private javax.swing.JPanel pnCatRight;
    private javax.swing.JSpinner spinLCBLuong;
    private javax.swing.JSpinner spinLCBLuongFind;
    private javax.swing.JTable tbUser;
    private javax.swing.JTextField tfUserId;
    private javax.swing.JTextField tfUserIdFind;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btUserThem){
       rowCount=tbUser.getRowCount();
               
          LuongCoBan lcb=new LuongCoBan(0,(double)spinLCBLuong.getValue());
          if(controller.add(lcb)>0){
          loadTable(null);
          tbUser.setRowSelectionInterval(rowCount,rowCount);
          JOptionPane.showMessageDialog(null,"Thêm thành công");
          return;
          }
      }
      if(e.getSource()==btUserXoa){
         
          int id=0;
          if(crow>=0){
              id=Integer.parseInt(tfUserId.getText());
          }
       LuongCoBan lcb=new LuongCoBan(id, 0);
          if(controller.delete(lcb)>0){
                 loadTable(null);
                 resetForm();
          JOptionPane.showMessageDialog(null,"Xóa thành công");
         
          }
      }
      if(e.getSource()==btUserNhapLai){
          resetForm();
      }
      if(e.getSource()==btUserSua){
       crow=tbUser.getSelectedRow();
          System.out.println(crow);
          int id=0;
          if(crow>=0){
              id=Integer.parseInt(tfUserId.getText());
          }
         LuongCoBan lcb=new LuongCoBan(id,(double) spinLCBLuong.getValue());
           if(controller.edit(lcb)>0){
                 loadTable(null);
                 tbUser.setRowSelectionInterval(crow,crow);
                 resetForm();
          JOptionPane.showMessageDialog(null,"Sửa thành công");
         
          }
      }
      if(e.getSource()==btUserSearch){
         
          int id=0;
          if(!"".equals(tfUserIdFind.getText())){
              try{
              id=Integer.parseInt(tfUserIdFind.getText());
              }catch(NumberFormatException ex){
                  JOptionPane.showMessageDialog(null, "Vui lòng nhập vào Id là số");
              }
          }
            LuongCoBan lcb=new LuongCoBan(id,(double) spinLCBLuongFind.getValue());
           loadTable(lcb);
           resetForm();
      }
    }
}
