/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view1;

import bean.About;
import controller.ControllerAbout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Date;
import java.util.Vector;
import javafx.scene.control.SplitPane;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 */
public class PnTSThongTinQuan extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form PnCat
     */
    private controller.ControllerAbout controllerAbout;
    private About about;

    public PnTSThongTinQuan() {
        initComponents();
        controllerAbout = new ControllerAbout();

        setForm();
    
     
    }
    public Time convertToTime(JSpinner sp){
        Date date =(Date) sp.getValue();
        long time=date.getTime();
        Time t=new Time(time);
        return t;
    }

    public void setForm() {
        about = controllerAbout.getAbout();
        tfThongTinQuanTen.setText(about.getTenQuan_about());
        tfThongTinQuanDiaChi.setText(about.getAddress_about());
        tfThongTinQuanSDT.setText(about.getSdt_about());
        tfThongTinQuanTenChuQuan.setText(about.getChuQuan_about());
        spinThoiGianMoCua.setValue(about.getGioMoCua());
        spinThoiGianDongCua.setValue(about.getGioDongCua());
        revalidate();
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCatLeft = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfThongTinQuanTenChuQuan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfThongTinQuanDiaChi = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btThongTinQuanSua = new javax.swing.JButton();
        btThongTinQuanNhapLai = new javax.swing.JButton();
        tfThongTinQuanTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinThoiGianMoCua = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spinThoiGianDongCua = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        tfThongTinQuanSDT = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        pnCatLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Form chức năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        pnCatLeft.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Tên quán cà phê của bạn :");

        tfThongTinQuanTenChuQuan.setMinimumSize(new java.awt.Dimension(6, 26));
        tfThongTinQuanTenChuQuan.setPreferredSize(new java.awt.Dimension(6, 32));
        tfThongTinQuanTenChuQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfThongTinQuanTenChuQuanActionPerformed(evt);
            }
        });

        jLabel2.setText("Địa chỉ:");

        tfThongTinQuanDiaChi.setPreferredSize(new java.awt.Dimension(6, 32));

        btThongTinQuanSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btThongTinQuanSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btThongTinQuanSua.setText("Sửa");
        btThongTinQuanSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongTinQuanSuaActionPerformed(evt);
            }
        });

        btThongTinQuanNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btThongTinQuanNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btThongTinQuanNhapLai.setText("Nhập lại");
        btThongTinQuanNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongTinQuanNhapLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btThongTinQuanSua, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btThongTinQuanNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btThongTinQuanNhapLai, btThongTinQuanSua});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btThongTinQuanNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btThongTinQuanSua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tfThongTinQuanTen.setMinimumSize(new java.awt.Dimension(6, 26));
        tfThongTinQuanTen.setPreferredSize(new java.awt.Dimension(6, 32));

        jLabel3.setText("Tên chủ quán:");

        jLabel4.setText("Thời gian mở cửa:");

        spinThoiGianMoCua.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        spinThoiGianMoCua.setEditor(new javax.swing.JSpinner.DateEditor(spinThoiGianMoCua, "hh:mm a"));

        jLabel5.setText("Thời gian đóng cửa:");

        spinThoiGianDongCua.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        spinThoiGianDongCua.setEditor(new javax.swing.JSpinner.DateEditor(spinThoiGianDongCua, "hh:mm a"));

        jLabel6.setText("Số điện thoại:");

        tfThongTinQuanSDT.setMinimumSize(new java.awt.Dimension(6, 26));
        tfThongTinQuanSDT.setPreferredSize(new java.awt.Dimension(6, 32));
        tfThongTinQuanSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfThongTinQuanSDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfThongTinQuanTenChuQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfThongTinQuanDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfThongTinQuanTen, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfThongTinQuanSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(spinThoiGianMoCua, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spinThoiGianDongCua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfThongTinQuanTen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfThongTinQuanDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfThongTinQuanTenChuQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfThongTinQuanSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinThoiGianDongCua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinThoiGianMoCua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {spinThoiGianDongCua, spinThoiGianMoCua, tfThongTinQuanDiaChi, tfThongTinQuanSDT, tfThongTinQuanTen, tfThongTinQuanTenChuQuan});

        pnCatLeft.add(jPanel1, new java.awt.GridBagConstraints());

        add(pnCatLeft, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tfThongTinQuanTenChuQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfThongTinQuanTenChuQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfThongTinQuanTenChuQuanActionPerformed

    private void btThongTinQuanSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongTinQuanSuaActionPerformed
        // TODO add your handling code here:
        about = new About(tfThongTinQuanTen.getText(), tfThongTinQuanDiaChi.getText(), tfThongTinQuanSDT.getText(), tfThongTinQuanTenChuQuan.getText(), convertToTime(spinThoiGianMoCua),convertToTime(spinThoiGianDongCua));
       if(controllerAbout.setAbout(about)>0){
           setForm();
           JOptionPane.showMessageDialog(this,"Thành công");
       }
    }//GEN-LAST:event_btThongTinQuanSuaActionPerformed

    private void tfThongTinQuanSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfThongTinQuanSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfThongTinQuanSDTActionPerformed

    private void btThongTinQuanNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongTinQuanNhapLaiActionPerformed
        // TODO add your handling code here:
        setForm();
    }//GEN-LAST:event_btThongTinQuanNhapLaiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btThongTinQuanNhapLai;
    private javax.swing.JButton btThongTinQuanSua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnCatLeft;
    private javax.swing.JSpinner spinThoiGianDongCua;
    private javax.swing.JSpinner spinThoiGianMoCua;
    private javax.swing.JTextField tfThongTinQuanDiaChi;
    private javax.swing.JTextField tfThongTinQuanSDT;
    private javax.swing.JTextField tfThongTinQuanTen;
    private javax.swing.JTextField tfThongTinQuanTenChuQuan;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

    }

}
