/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view1;

import bean.LoaiThucUong;
import controller.ControllerKhuVuc;
import controller.ControllerLoaiThucUong;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JSplitPane;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import library.LibraryDimension;
import renderer.TableCellRendererColor;
import renderer.TableCellRendererHeaderColumn;

/**
 *
 * @author hominhhuy
 */
public class PnTSLoaiThucUong extends javax.swing.JPanel implements ActionListener {

    private DefaultTableModel model;
    private int crow;
    private int rowCount = 0;
    private controller.ControllerLoaiThucUong controller;
    private boolean ckTT = false;
    private JTableHeader header;
    /**
     * Creates new form PnCat
     */
    public PnTSLoaiThucUong() {
        initComponents();
        btLTUNhapLai.addActionListener(this);
        btLTUSua.addActionListener(this);
        btLTUThem.addActionListener(this);
        crow = -1;
        controller = new ControllerLoaiThucUong();
        //set split pane
        JSplitPane sp = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, pnCatLeft, pnCatRight);
        sp.setOneTouchExpandable(true);
        add(sp);
//        pnCatLeft.setMinimumSize(new Dimension(LibraryDimension.PANEL_LEFT_WIDTH, pnCatLeft.getSize().height));
        model = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0 || columnIndex == 3) {
                    return Integer.class;
                }
                if (columnIndex == 6) {
                    return Boolean.class;
                }

                return super.getColumnClass(columnIndex);
            }

        };
        loadTable(null, true);
        header=tbLoaiThucUong.getTableHeader();
        header.addMouseListener(new TableCellRendererHeaderColumn(tbLoaiThucUong));

        //((JComponent) tbLoaiThucUong.getDefaultRenderer(Boolean.class)).setOpaque(true);

    }

    public void loadTable(LoaiThucUong ltu, boolean ctt) {
        controller.loadTable(tbLoaiThucUong, model, ltu,ctt);

        setRowsColor();

    }

    public void setRowsColor() {
        ArrayList<Integer> alRowsMax10 = new ArrayList();
        ArrayList<Integer> alRowsMin10 = new ArrayList();
        ArrayList<Integer> alRowsActive = new ArrayList();

        rowCount = tbLoaiThucUong.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            int sl = (int) tbLoaiThucUong.getValueAt(i, 3);
            if (sl <= 10) {
                alRowsMax10.add(i);
            }
            if (sl > 10) {
                alRowsMin10.add(i);
            }

        }
        for (int j = 0; j < tbLoaiThucUong.getColumnCount(); j++) {
            tbLoaiThucUong.getColumnModel().getColumn(j).setCellRenderer(new TableCellRendererColor(alRowsMax10, alRowsMin10));
        }
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCatLeft = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfLTUId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfLTUName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btLTUThem = new javax.swing.JButton();
        btLTUSua = new javax.swing.JButton();
        btLTUNhapLai = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btNewsUpload = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        spinLTUGia = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinLTUSoLuong = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        tfLTUDonVi = new javax.swing.JTextField();
        ckBoxTrangThai = new javax.swing.JCheckBox();
        btKTTT = new javax.swing.JButton();
        pnCatRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLoaiThucUong = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfLTUIdFind = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfLTUNameFind = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        spinLTUGiaS = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        spinTUGiaE = new javax.swing.JSpinner();
        btLTUGiaActiveFind = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        spinTUSoLuongS = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        spinTUSoLuongE = new javax.swing.JSpinner();
        btLTUSoLuongActiveFind = new javax.swing.JButton();
        ckBoxTTFind = new javax.swing.JCheckBox();
        btLTUTTActive = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btLTUTimKiemFind = new javax.swing.JButton();
        btLTUNhapLaiFind = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnCatLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Form chức năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        pnCatLeft.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Mã thức uống:");

        tfLTUId.setEnabled(false);
        tfLTUId.setPreferredSize(new java.awt.Dimension(6, 26));

        jLabel2.setText("Tên thức uống:");

        tfLTUName.setPreferredSize(new java.awt.Dimension(6, 32));

        btLTUThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLTUThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btLTUThem.setText("Thêm");
        jPanel3.add(btLTUThem);

        btLTUSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLTUSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btLTUSua.setText("Sửa");
        btLTUSua.setPreferredSize(new java.awt.Dimension(85, 25));
        jPanel3.add(btLTUSua);

        btLTUNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLTUNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btLTUNhapLai.setText("Nhập lại");
        btLTUNhapLai.setPreferredSize(new java.awt.Dimension(95, 25));
        btLTUNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLTUNhapLaiActionPerformed(evt);
            }
        });
        jPanel3.add(btLTUNhapLai);

        jLabel6.setText("Hình ảnh:");

        btNewsUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload.png"))); // NOI18N
        btNewsUpload.setText("Upload");
        btNewsUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewsUploadActionPerformed(evt);
            }
        });

        jLabel7.setText("Giá  :");

        spinLTUGia.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(5.0d)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.png"))); // NOI18N

        jLabel8.setText("Số lượng:");

        spinLTUSoLuong.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(5)));

        jLabel9.setText("Đơn vị :");

        tfLTUDonVi.setPreferredSize(new java.awt.Dimension(6, 26));

        ckBoxTrangThai.setText("Còn hàng");
        ckBoxTrangThai.setEnabled(false);
        ckBoxTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBoxTrangThaiActionPerformed(evt);
            }
        });

        btKTTT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btKTTT.setForeground(java.awt.Color.green);
        btKTTT.setText("V");
        btKTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKTTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLTUName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btNewsUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(tfLTUId, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(ckBoxTrangThai)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btKTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(spinLTUGia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(spinLTUSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfLTUDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 110, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfLTUId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfLTUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinLTUSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinLTUGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLTUDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btKTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckBoxTrangThai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNewsUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {spinLTUSoLuong, tfLTUId, tfLTUName});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btNewsUpload, spinLTUGia});

        pnCatLeft.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(pnCatLeft, java.awt.BorderLayout.LINE_START);

        pnCatRight.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 0))); // NOI18N
        pnCatRight.setLayout(new java.awt.BorderLayout());

        tbLoaiThucUong.setAutoCreateRowSorter(true);
        tbLoaiThucUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tbLoaiThucUong.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbLoaiThucUong.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tbLoaiThucUongAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbLoaiThucUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLoaiThucUongMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbLoaiThucUongMousePressed(evt);
            }
        });
        tbLoaiThucUong.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                tbLoaiThucUongComponentMoved(evt);
            }
        });
        tbLoaiThucUong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbLoaiThucUongKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbLoaiThucUong);

        pnCatRight.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Mã thức uống:");

        tfLTUIdFind.setPreferredSize(new java.awt.Dimension(6, 32));

        jLabel10.setText("Tên thức uống:");

        jLabel12.setText("Giá:");

        spinLTUGiaS.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));
        spinLTUGiaS.setToolTipText("");
        spinLTUGiaS.setEnabled(false);

        jLabel13.setText("Đến");

        spinTUGiaE.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(5.0d), null, null, Double.valueOf(1.0d)));
        spinTUGiaE.setEnabled(false);
        spinTUGiaE.setFocusable(false);

        btLTUGiaActiveFind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLTUGiaActiveFind.setForeground(java.awt.Color.green);
        btLTUGiaActiveFind.setText("V");
        btLTUGiaActiveFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLTUGiaActiveFindActionPerformed(evt);
            }
        });

        jLabel14.setText("Số lượng:");

        spinTUSoLuongS.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinTUSoLuongS.setEnabled(false);
        spinTUSoLuongS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spinTUSoLuongSMouseClicked(evt);
            }
        });

        jLabel15.setText("Đến");

        spinTUSoLuongE.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(5), Integer.valueOf(0), null, Integer.valueOf(1)));
        spinTUSoLuongE.setEnabled(false);
        spinTUSoLuongE.setFocusable(false);

        btLTUSoLuongActiveFind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLTUSoLuongActiveFind.setForeground(java.awt.Color.green);
        btLTUSoLuongActiveFind.setText("V");
        btLTUSoLuongActiveFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLTUSoLuongActiveFindActionPerformed(evt);
            }
        });

        ckBoxTTFind.setText("Active");
        ckBoxTTFind.setEnabled(false);
        ckBoxTTFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBoxTTFindActionPerformed(evt);
            }
        });

        btLTUTTActive.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLTUTTActive.setForeground(java.awt.Color.green);
        btLTUTTActive.setText("V");
        btLTUTTActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLTUTTActiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ckBoxTTFind)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfLTUIdFind, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel14))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spinTUSoLuongS, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spinLTUGiaS, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLTUNameFind))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(spinTUSoLuongE, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btLTUSoLuongActiveFind))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(21, 21, 21)
                                .addComponent(spinTUGiaE, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(btLTUGiaActiveFind))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLTUTTActive))))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btLTUGiaActiveFind, btLTUSoLuongActiveFind, btLTUTTActive});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ckBoxTTFind, spinTUSoLuongS});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfLTUIdFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfLTUNameFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinLTUGiaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(spinTUGiaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLTUGiaActiveFind))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinTUSoLuongS, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(spinTUSoLuongE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLTUSoLuongActiveFind))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckBoxTTFind)
                    .addComponent(btLTUTTActive))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btLTUGiaActiveFind, btLTUSoLuongActiveFind, btLTUTTActive, ckBoxTTFind, spinLTUGiaS, spinTUGiaE, spinTUSoLuongE, spinTUSoLuongS, tfLTUIdFind, tfLTUNameFind});

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel5.setLayout(new java.awt.GridLayout(3, 1, 0, 8));

        btLTUTimKiemFind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLTUTimKiemFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        btLTUTimKiemFind.setText("Tìm kiếm");
        btLTUTimKiemFind.setPreferredSize(new java.awt.Dimension(130, 23));
        btLTUTimKiemFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLTUTimKiemFindActionPerformed(evt);
            }
        });
        jPanel5.add(btLTUTimKiemFind);

        btLTUNhapLaiFind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLTUNhapLaiFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btLTUNhapLaiFind.setText("Nhập lại");
        jPanel5.add(btLTUNhapLaiFind);

        jPanel2.add(jPanel5, java.awt.BorderLayout.EAST);

        pnCatRight.add(jPanel2, java.awt.BorderLayout.NORTH);

        add(pnCatRight, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btLTUNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLTUNhapLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLTUNhapLaiActionPerformed

    private void btLTUTimKiemFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLTUTimKiemFindActionPerformed
        // TODO add your handling code here:
        LoaiThucUong ltu = new LoaiThucUong();
        int id = 0;
        if (!"".equals(tfLTUIdFind.getText())) {
            try {
                id = Integer.parseInt(tfLTUIdFind.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập vào id là số");
            }

        }
        ltu.setId_ltu(id);
        //GIa
        double gS = -1;
        double gE = -1;
        if ("X".equals(btLTUGiaActiveFind.getText())) {
            if ((double) spinLTUGiaS.getValue() > (double) spinTUGiaE.getValue()) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn giá khởi điểm nhỏ hơn giá lớn nhất");
            } else {
                gE = (double) spinTUGiaE.getValue();
                gS = (double) spinLTUGiaS.getValue();
            }
        }
        ltu.setGiaMax_ltu(gE);
        ltu.setGia_ltu(gS);
        //Số lượng
        int sLS = -1;
        int sLE = -1;
        if ("X".equals(btLTUSoLuongActiveFind.getText())) {
            if ((int) spinTUSoLuongS.getValue() > (int) spinTUSoLuongE.getValue()) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn số lượng khởi điểm nhỏ hơn giá lớn nhất");
            } else {
                sLS = (int) spinTUSoLuongS.getValue();
                sLE = (int) spinTUSoLuongE.getValue();
            }
        }
        ltu.setSoLuongMax_ltu(sLE);
        ltu.setSoLuong_ltu(sLS);
        ltu.setTen_ltu(tfLTUNameFind.getText());
               
        boolean ck=false;
        if ("X".equals(btLTUTTActive.getText())) {
            ck = true;
            ltu.setTrangThai_ltu(ckBoxTTFind.isSelected());
        }
        loadTable(ltu, ck);
        System.out.println(ck);
        resetForm();
    }//GEN-LAST:event_btLTUTimKiemFindActionPerformed

    private void tbLoaiThucUongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLoaiThucUongMousePressed
        // TODO add your handling code here:
        setForm();

    }//GEN-LAST:event_tbLoaiThucUongMousePressed

    private void tbLoaiThucUongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbLoaiThucUongKeyReleased
        // TODO add your handling code here:
        setForm();

    }//GEN-LAST:event_tbLoaiThucUongKeyReleased

    private void btNewsUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewsUploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNewsUploadActionPerformed

    private void btLTUGiaActiveFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLTUGiaActiveFindActionPerformed
        // TODO add your handling code here:
        if ("X".equals(btLTUGiaActiveFind.getText())) {
            btLTUGiaActiveFind.setText("V");
            btLTUGiaActiveFind.setForeground(Color.GREEN);
            spinLTUGiaS.setEnabled(false);
            spinTUGiaE.setEnabled(false);

        } else if ("V".equals(btLTUGiaActiveFind.getText())) {
            btLTUGiaActiveFind.setText("X");
            btLTUGiaActiveFind.setForeground(new Color(205, 0, 0));
            spinLTUGiaS.setEnabled(true);
            spinTUGiaE.setEnabled(true);
        }

    }//GEN-LAST:event_btLTUGiaActiveFindActionPerformed

    private void ckBoxTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBoxTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckBoxTrangThaiActionPerformed

    private void tbLoaiThucUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLoaiThucUongMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tbLoaiThucUongMouseClicked

    private void tbLoaiThucUongAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbLoaiThucUongAncestorMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_tbLoaiThucUongAncestorMoved

    private void tbLoaiThucUongComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tbLoaiThucUongComponentMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_tbLoaiThucUongComponentMoved

    private void btKTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKTTTActionPerformed
        // TODO add your handling code here:
        if ("X".equals(btKTTT.getText())) {
            btKTTT.setText("V");
            btKTTT.setForeground(Color.GREEN);
            ckBoxTrangThai.setEnabled(false);
        } else if ("V".equals(btKTTT.getText())) {
            btKTTT.setText("X");
            btKTTT.setForeground(new Color(205, 0, 0));
            ckBoxTrangThai.setEnabled(true);
        }

    }//GEN-LAST:event_btKTTTActionPerformed

    private void btLTUSoLuongActiveFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLTUSoLuongActiveFindActionPerformed
        // TODO add your handling code here:
        if ("X".equals(btLTUSoLuongActiveFind.getText())) {
            btLTUSoLuongActiveFind.setText("V");
            btLTUSoLuongActiveFind.setForeground(Color.GREEN);
            spinTUSoLuongS.setEnabled(false);
            spinTUSoLuongE.setEnabled(false);

        } else if ("V".equals(btLTUSoLuongActiveFind.getText())) {
            btLTUSoLuongActiveFind.setText("X");
            btLTUSoLuongActiveFind.setForeground(new Color(205, 0, 0));
            spinTUSoLuongS.setEnabled(true);
            spinTUSoLuongE.setEnabled(true);
        }

    }//GEN-LAST:event_btLTUSoLuongActiveFindActionPerformed

    private void spinTUSoLuongSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinTUSoLuongSMouseClicked
        // TODO add your handling code here:
        System.out.println("á");
    }//GEN-LAST:event_spinTUSoLuongSMouseClicked

    private void btLTUTTActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLTUTTActiveActionPerformed
        // TODO add your handling code here:
        if ("X".equals(btLTUTTActive.getText())) {
            btLTUTTActive.setText("V");
            btLTUTTActive.setForeground(Color.GREEN);
            ckBoxTTFind.setEnabled(false);
        } else if ("V".equals(btLTUTTActive.getText())) {
            btLTUTTActive.setText("X");
            btLTUTTActive.setForeground(new Color(205, 0, 0));
            ckBoxTTFind.setEnabled(true);
        }


    }//GEN-LAST:event_btLTUTTActiveActionPerformed

    private void ckBoxTTFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBoxTTFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckBoxTTFindActionPerformed
    public void setForm() {
        crow = tbLoaiThucUong.getSelectedRow();
        tfLTUId.setText(tbLoaiThucUong.getValueAt(crow, 0).toString());
        tfLTUName.setText(tbLoaiThucUong.getValueAt(crow, 1).toString());
        spinLTUGia.setValue(tbLoaiThucUong.getValueAt(crow, 2));
        spinLTUSoLuong.setValue(tbLoaiThucUong.getValueAt(crow, 3));
        tfLTUDonVi.setText(tbLoaiThucUong.getValueAt(crow, 4).toString());
        if ((boolean) tbLoaiThucUong.getValueAt(crow, 6) == true) {
            ckBoxTrangThai.setSelected(true);
        } else {
            ckBoxTrangThai.setSelected(false);
        }
    }

    public void resetForm() {
        tfLTUId.setText("");
        tfLTUName.setText("");
        spinLTUGia.setValue(0);
        spinLTUSoLuong.setValue(0);
        tfLTUDonVi.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btKTTT;
    private javax.swing.JButton btLTUGiaActiveFind;
    private javax.swing.JButton btLTUNhapLai;
    private javax.swing.JButton btLTUNhapLaiFind;
    private javax.swing.JButton btLTUSoLuongActiveFind;
    private javax.swing.JButton btLTUSua;
    private javax.swing.JButton btLTUTTActive;
    private javax.swing.JButton btLTUThem;
    private javax.swing.JButton btLTUTimKiemFind;
    private javax.swing.JButton btNewsUpload;
    private javax.swing.JCheckBox ckBoxTTFind;
    private javax.swing.JCheckBox ckBoxTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnCatLeft;
    private javax.swing.JPanel pnCatRight;
    private javax.swing.JSpinner spinLTUGia;
    private javax.swing.JSpinner spinLTUGiaS;
    private javax.swing.JSpinner spinLTUSoLuong;
    private javax.swing.JSpinner spinTUGiaE;
    private javax.swing.JSpinner spinTUSoLuongE;
    private javax.swing.JSpinner spinTUSoLuongS;
    private javax.swing.JTable tbLoaiThucUong;
    private javax.swing.JTextField tfLTUDonVi;
    private javax.swing.JTextField tfLTUId;
    private javax.swing.JTextField tfLTUIdFind;
    private javax.swing.JTextField tfLTUName;
    private javax.swing.JTextField tfLTUNameFind;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btLTUThem) {
            boolean tt = ckBoxTrangThai.isSelected();

            LoaiThucUong ltu = new LoaiThucUong(0, tfLTUName.getText().toString(), (double) spinLTUGia.getValue(), (int) spinLTUSoLuong.getValue(), tfLTUDonVi.getText(), "hinh1.jpg", tt);
            if (controller.add(ltu) > 0) {
                rowCount = tbLoaiThucUong.getRowCount();
                System.out.println(rowCount);
                loadTable(null, false);
                tbLoaiThucUong.setRowSelectionInterval(rowCount-1, rowCount-1);
                resetForm();
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                return;
            }
        }
        if (e.getSource() == btLTUNhapLai) {
            resetForm();
        }
        if (e.getSource() == btLTUSua) {
            crow = tbLoaiThucUong.getSelectedRow();
            System.out.println(crow);
            int id = 0;
            if (crow >= 0) {
                id = Integer.parseInt(tfLTUId.getText());
            }

            LoaiThucUong ltu = new LoaiThucUong(id, tfLTUName.getText(), (double) spinLTUGia.getValue(), (int) spinLTUSoLuong.getValue(), tfLTUDonVi.getText(), "hinh1.jpg", ckBoxTrangThai.isSelected());
            if (controller.edit(ltu) > 0) {
                loadTable(null, false);
                tbLoaiThucUong.setRowSelectionInterval(crow, crow);
                resetForm();
                JOptionPane.showMessageDialog(null, "Sửa thành công");

            }
        }
//        if(e.getSource()==btLTUXoa){
//            int id=0;
//            if(!"".equals(tfLTUId.getText())){
//                    id=Integer.parseInt(tfLTUId.getText());
//            }
//            
//                LoaiThucUong ltu=new LoaiThucUong(id,null,0,0,"","");
//                if(controller.delete(ltu)>0){
//                 rowCount=tbLoaiThucUong.getRowCount();
//                    loadTable(null);
//          tbLoaiThucUong.setRowSelectionInterval(rowCount,rowCount);
//          JOptionPane.showMessageDialog(null,"Thêm thành công");
//          return;
//                }  
//        }

    }
}
